### ISSUE TITLE
Preview service DB connection issue

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-server#518]
Probably related to knex / nodejs versions, since the upgrade to node 16, this error sometimes happen for long-running containers:

```
Error executing task:  KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/opt/preview-service/node_modules/knex/lib/client.js:305:26)
    at async Runner.ensureConnection (/opt/preview-service/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/opt/preview-service/node_modules/knex/lib/execution/runner.js:30:19)
    at async startTask (/opt/preview-service/bg_service/index.js:10:18)
    at async Timeout.tick [as _onTimeout] (/opt/preview-service/bg_service/index.js:76:16) {
  sql: '\n' +
    '    UPDATE object_preview\n' +
    '    SET \n' +
    '      "previewStatus" = 1,\n' +
    '      "lastUpdate" = NOW()\n' +
    '    FROM (\n' +
    '      SELECT "streamId", "objectId" FROM object_preview\n' +
    `      WHERE "previewStatus" = 0 OR ("previewStatus" = 1 AND "lastUpdate" < NOW() - INTERVAL '1 WEEK')\n` +
    '      ORDER BY "priority" ASC, "lastUpdate" ASC\n' +
    '      LIMIT 1\n' +
    '    ) as task\n' +
    '    WHERE object_preview."streamId" = task."streamId" AND object_preview."objectId" = task."objectId"\n' +
    '    RETURNING object_preview."streamId", object_preview."objectId"\n' +
    '  ',
  bindings: undefined
}
```

**Comment by cristi8** [comment]
Couldn't reproduce locally.

Reverted base image to node 14, increased the max db connections from 1 to 2 for previewservice, making ticket to upgrade dependencies next sprint
