### ISSUE TITLE
Preview service pod keeps restarting in production

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#947]
Investigate what causes the preview service pod to restart in production clusters.

![image](https://user-images.githubusercontent.com/57442769/185581536-5dc24b9a-39f6-4069-9634-40c4c01d379b.png)

**Comment by iainsproat** [comment]
```
POST /api/getobjects/069dcc48fb 200 9.644 ms - -
Streamed 37633 objects from stream 069dcc48fb (size: 54.843866 MB)
/speckle-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:325
        this.emit('error', new Error('Page crashed!'));
                           ^

Error: Page crashed!
    at Page._onTargetCrashed (/speckle-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:325:28)
    at /speckle-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:155:57
    at /speckle-server/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/speckle-server/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/speckle-server/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (/speckle-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:249:18)
    at Connection._onMessage (/speckle-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:117:25)
    at WebSocket.<anonymous> (/speckle-server/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (/speckle-server/node_modules/ws/lib/event-target.js:199:18)
 ```

**Comment by iainsproat** [comment]
Previous logs from the other pod for xyz:
```
POST /api/getobjects/9b692137ca 200 187.845 ms - -
Streamed 52682 objects from stream 9b692137ca (size: 25.542577 MB)
Shutting down...
```

**Comment by gjedlicska** [comment]
It would be nice to correlate this with metrics, maybe the crash was caused by lack of available resources.
